(cl:defpackage play_motion_msgs-msg
  (:use )
  (:export
   "<MOTIONINFO>"
   "MOTIONINFO"
   "<PLAYMOTIONACTIONRESULT>"
   "PLAYMOTIONACTIONRESULT"
   "<PLAYMOTIONFEEDBACK>"
   "PLAYMOTIONFEEDBACK"
   "<PLAYMOTIONACTIONGOAL>"
   "PLAYMOTIONACTIONGOAL"
   "<PLAYMOTIONRESULT>"
   "PLAYMOTIONRESULT"
   "<PLAYMOTIONACTIONFEEDBACK>"
   "PLAYMOTIONACTIONFEEDBACK"
   "<PLAYMOTIONGOAL>"
   "PLAYMOTIONGOAL"
   "<PLAYMOTIONACTION>"
   "PLAYMOTIONACTION"
  ))

